version: "3.8"

services:
  frontend:
    image: ghcr.io/childmindresearch/linguaweb-frontend:main
    ports:
      - 3000:3000
    environment:
      - VITE_API_URL=http://api:8000
    networks:
      - frontend_api

  api:
    image: ghcr.io/childmindresearch/linguaweb-api:main
    ports:
      - 8000:8000
    environment:
      - LWAPI_OPENAI_API_KEY=${OPENAI_API_KEY}
      - LWAPI_POSTGRES_USER=${POSTGRES_USER}
      - LWAPI_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - LWAPI_POSTGRES_HOST=postgresql
      - LWAPI_POSTGRES_PORT=5432
      - LWAPI_S3_ACCESS_KEY=${MINIO_ROOT_USER}
      - LWAPI_S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - LWAPI_S3_ENDPOINT_URL=http://minio:9000
    networks:
      - frontend_api
      - api_postgresql
      - api_minio

  postgresql:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - api_postgresql

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio:/data
    networks:
      - api_minio
    command: server --address ":9000" --console-address ":9001" /data



networks:
  frontend_api:
  api_postgresql:
  api_minio:
